from platform import freedesktop_os_release
from datetime import datetime
from time import sleep
from os import path

import os
import subprocess
import ui
import json
import secrets
import shutil

logo       = r'''
    ▄▄▄                          ▄▄ ▄▄       
   ██▀▀█▄             █▄          ██ ██      
   ██ ▄█▀             ██          ██ ██      
   ██▀▀█▄ ▄▀▀█▄ ▄██▀█ ████▄ ▄█▀█▄ ██ ██ ▄█▀█▄
 ▄ ██  ▄█ ▄█▀██ ▀███▄ ██ ██ ██▄█▀ ██ ██ ██▄█▀
 ▀██████▀▄▀█▄███▄▄██▀▄██ ██▄▀█▄▄▄▄██▄██▄▀█▄▄▄                                        
                 by anzar
'''

config_home  = path.expanduser("~/.config")
local_home    = path.expanduser("~/.local")

supported_desktops = {
    "hyprland": "hypr",
}

base_dir    = path.join(path.dirname(__file__))
script_dir  = path.join(base_dir, "scripts")

def os_release() -> str:
    release = freedesktop_os_release()
    id      = release.get("ID", "")
    id_like = release.get("ID_LIKE", "")
    
    if (id == "arch" or "arch" in id_like):
        return "arch"
        
    return "not_supported"

def load_config(file):
    if not path.isfile(file): return None
    
    with open(file, "r") as f:
        return json.load(f)

def backup(name, target):
    if path.lexists(target):
        backup_dir = path.join(config_home, "bashelle", ".recovery", f"{name}")
        
        os.makedirs(backup_dir, exist_ok=True)
        
        ui.spinner(
            f"Creating backup for: {target}",
            subprocess.run,
            ["cp", "-rL", target, backup_dir]
        )
        
        with open(path.join(backup_dir, "meta.json"), "w") as f:
            json.dump({
                "description": "Generated by Bashelle installer",
                "when": datetime.now().isoformat()
            }, f, indent=2)

def install_dotfile(dotfile, name, track=True):
    git_path = path.join(config_home, "bashelle", name)
    target_path = path.join(config_home, name)
    
    lock_file = path.join(config_home, "bashelle", ".lock.json")
    
    if path.exists(git_path):
        subprocess.run(["rm", "-rf", git_path])
    
    # install dotfile
    ui.spinner(
        f"Cloning '{name}'",
        subprocess.run,
        ["git", "clone", "--branch", dotfile["tag/branch"], dotfile["git"], git_path],
        check=True,
        text=True,
        capture_output=True,
    )

    # creates symlink
    if path.lexists(target_path):
        subprocess.run(["rm", "-rf", target_path])
    
    subprocess.run(["ln", "-s", git_path, config_home])


    # updates lock file
    if track:
        revparse = subprocess.run(
            ["git", "-C", git_path, "rev-parse", "HEAD"], 
            capture_output=True,
            text=True
        )

        lock_data = {}
        if path.exists(lock_file):
            with open(lock_file, "r") as f:
                lock_data = json.load(f)
        
        lock_data[name] = {
            "tag/branch": dotfile["tag/branch"],
            "commit": revparse.stdout.strip()
        }

        with open(lock_file, "w") as f:
            json.dump(lock_data, f, indent=2)

    # cleans git files
    subprocess.run(["rm", "-rf", path.join(git_path, ".git"), path.join(git_path, ".gitignore")])


def start_daemons(daemons):
    for daemon in daemons:
        running = subprocess.run(["pgrep", "-x", daemon], stdout=subprocess.DEVNULL).returncode == 0
        if not running:
            subprocess.Popen(
                [daemon], 
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL
            )

